meta_title: "Monsieur Mode Shop ▻ Boutique Homme, Vêtements Chaussures Accessoires"
meta_description: "Toute la mode homme est en vente sur la boutique ! Vêtements, chaussures & accessoires de marques à prix cassés !"
meta_image: "logo-monsieur-mode-shop.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@MonsieurMode" # indispensable pour les Twitter Cards
meta_keyword: "mode homme, mode masculine, magasin masculin, magasin homme, relooking homme, style homme, look homme, vêtements homme, mode au masculin, conseils mode masculine"
