meta_title: "Monsieur Mode Shop - Boutique Vetements Homme"
meta_description: "Toute la mode homme réunie dans une seule boutique ! Vêtements, chaussures, accessoires de mode masculine."
meta_image: "logo-adopte-un-style.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@MonsieurMode" # indispensable pour les Twitter Cards
